name=SwitchMatrix
version=0.1.0
author=ve-cto <arkusarkus135@gmail.com>
maintainer=ve-cto <arkusarkus135@gmail.com>
sentence=Library for interfacing with button/switch diode matrices.
paragraph=
category=Signal Input/Output
url=https://github.com/ve-cto/ButtonMatrixLib
architectures=*