name=SwitchMatrixLib
version=1.0.3
author=ve-cto <arkusarkus135@gmail.com>
maintainer=ve-cto <arkusarkus135@gmail.com>
sentence=Library for interfacing with button/switch diode matrices.
paragraph=
category=Signal Input/Output
url=https://github.com/ve-cto/SwitchMatrixLib
architectures=esp32, esp8266, samd, sam, mbed, mbed_nano, mbed_portenta, mbed_rp2040, rp2040, stm32, renesas, renesas_uno, renesas_portenta
